### ISSUE TITLE
unmatched double quote

### ISSUE THREAD

**Issue by dtenenba** [aws-samples/aws-genomics-workflows#100]
On this line:

https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/aws-genomics-launch-template.template.yaml#L51

There is a missing double quote:

```
cd /usr/local/bin && curl --retry 5 --retry-connrefused $artifactRootUrl/fetch_and_run.sh" -o "fetch_and_run.sh" && chmod a+x ./fetch_and_run.sh
```

There should be a double quote before `$artifactRootUrl/...`. 

This is causing an error with instances that are trying to start with this launch template:

```
/var/lib/cloud/instance/scripts/runcmd: line 17: unexpected EOF while looking for matching `"'
/var/lib/cloud/instance/scripts/runcmd: line 20: syntax error: unexpected end of file
May 12 19:27:53 cloud-init[3067]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [2]
```

**Comment by wleepang** [comment]
Resolved in #101
