### ISSUE TITLE
GATK - NIO - S3 direct read access

### ISSUE THREAD

**Issue by JaeYJung** [aws-samples/aws-genomics-workflows#102]
Hello,

I have asked the same question to the GATK team, but I could not find any other AWS pages for this so asking here - is there any chance to make GATK read files directly from S3 near future? I believe it's a critical issue for large-scale joint calling pipeline.

**Comment by wleepang** [comment]
@JaeYJung 

This is an issue best submitted to the GATK project.

This project is for the AWS resources used to execute genomics workflows, but is otherwise agnostic of the tooling used for steps in said workflows.
