### ISSUE TITLE
Remove Static/Custom Names from AWS::Batch::ComputeEnvironment

### ISSUE THREAD

**Issue by senorkrabs** [aws-samples/aws-genomics-workflows#105]
`ComputeEnvironmentName` is specified in the AWS::Batch::ComputeEnvironment resources, which can prevent stack updates from succeeding when changes to the resource requires replacement.

**Example:**
>CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename spot-23b98780-1dbc-11ea-adc9-0ed2247e0ea9 and update the stack again.

Note: There may be other resources that are using static names that would cause similar issues. 

**Template locations:**
https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/aws-genomics-batch.template.yaml#L162
https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/aws-genomics-batch.template.yaml#L189

**Comment by wleepang** [comment]
The Batch ComputeEnvironment names are set to make them identifiable as belonging to a particular stack. This is useful when multiple stacks are deployed in the same account - e.g. for dev, test, and prod - so that user's know which resources can be safely modified.
