### ISSUE TITLE
changing workdir bucket

### ISSUE THREAD

**Issue by jcurado-flomics** [aws-samples/aws-genomics-workflows#106]
after creating successfully a compute environment I would like to change the workdir S3 bucket.

I tried to create a new bucket but the Nextflow pipelines don't work when I use it. How can I create a new valid bucket to be used as workdir by NF pipelines?

thank you very much in advance

**Comment by wleepang** [comment]
@jcurado-flomics - permissions to buckets are handled by IAM roles. For Nextflow there are two you need to modify if you need to change the bucket(s) it uses for `workDir` and for logs/caches (herein referred to as `logsDir`). Specifically, you need to update:

- Batch Job Instance Role
- Nextflow Job Role

You can get to these via the **Resources** tab of the CloudFormation stacks that created them. Note, the architectures use nested stacks, you will need to enable viewing nested stacks in the CloudFormation console.

Alternatively, you can create new stacks that specify the bucket(s) you intend to use.

**Comment by jcurado-flomics** [comment]
Thanks!

I managed to do it by following the **GWFCore (Existing VPC)** template from https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/

I created a new core of resources inside the previously created VPC.
