### ISSUE TITLE
issue with docker and EC2 launch template

### ISSUE THREAD

**Issue by SteveMarshallFSP** [aws-samples/aws-genomics-workflows#107]
Running from this example https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/ and noticed my jobs were failing. When I logged into the ec2 instance, it seems like docker isn't starting properly. 

Starting docker:	.[  OK  ]
start: Job failed to start
Oct 12 01:53:57 cloud-init[3203]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
Oct 12 01:53:57 cloud-init[3203]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/script
s)
Oct 12 01:53:57 cloud-init[3203]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/
python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 0.7.6 finished at Mon, 12 Oct 2020 01:53:57 +0000. Datasource DataSourceEc2.  Up 105.80 seconds

I've seen this issue before when it was using an older version of the AMI. I fixed this by adding this to my cloudformation template. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html

In the parameter section of my yaml file
  ECSAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: ECS-Optimized AMI ID
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

In the launch template resource section of my yaml file I add the ImageId: !Ref ECSAMI

**Comment by wleepang** [comment]
Thanks for bringing this to our attention. We'll take a look and get back you here.
