### ISSUE TITLE
EC2 immediately terminate with "Client.InternalError: Client error on launch" error.

### ISSUE THREAD

**Issue by DanielSochor** [aws-samples/aws-genomics-workflows#109]
We’ve deployed the "GWFCore (Existing VPC)" and "Nextflow Resources" stacks. We created a long running EC2 using an ECS optimized AMI and we have input data stored in S3. We have a nextflow.config file which sets the: 
-workDir, imageId, instanceType, securityGroup
Unfortunately when we launch the process from our long running EC2 the "batch on demand EC2" instances terminate immediately and the console displays this error "Client.InternalError: Client error on launch". We thought this error might be due to encrypted issues on the EBS volumes attached to the EC2s. We're adjusted the template to remove this EBS encryption but this did not solve the issue. 
Any idea what might be causing this issue?

**Comment by wleepang** [comment]
Will look into this and get back to you here.

**Comment by wleepang** [comment]
We recently pushed a major update to the templates. Can you redeploy updated stacks to see if this resolves your issue?

**Comment by DanielSochor** [comment]
We were able to get the v3.0.0 release of the templates working, thank you!
