### ISSUE TITLE
gwfcore-code.template.yaml

### ISSUE THREAD

**Issue by viralpatel94** [aws-samples/aws-genomics-workflows#110]
We cloned the root templates located here to a local bucket and made the template url changes accordingly.

https://github.com/aws-samples/aws-genomics-workflows/tree/master/src/templates/gwfcore

We are getting the below error and I think it's due to the 'aws-genomics-workflows' bucket not having proper permissions on the 'aws-ecs-additions.zip' object. As you can tell from the errors it's occurring in the latest merged child template called "CodeStack." Is this object public? Can we use the latest merged changes?

![image](https://user-images.githubusercontent.com/39914625/96511920-5be8b780-1225-11eb-8201-f6f4f0d7a722.png)

The linked root template in this the Nextflow quickstart webpage, still point to the old templates:
https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/

**Comment by tthyer** [comment]
I was having the same issue today, and agree it would be preferable if we could read from the default bucket. In the meantime, here is a workaround: run `scripts/make-dist.sh`. This will put all the artifacts in `dist/artifacts`. You can then upload these to an S3 bucket and folder of your own, then set the parameters `ArtifactBucketName` and `ArtifactBucketPrefix` (the latter for the folder).

**Comment by viralpatel94** [comment]
@tthyer I tried this actually, I got an empty aws-ecs-additions.tgz

**Comment by wleepang** [comment]
The site update lagged from the code update pending some CI issues. The site is updated now, and you can launch stacks from the launch buttons provided therein.

**Comment by wleepang** [comment]
This should be resolved in the latest patch release. If this is still a problem, feel free to re-open this issue.
