### ISSUE TITLE
ASSET_ROLE_ARN?

### ISSUE THREAD

**Issue by SteveMarshallFSP** [aws-samples/aws-genomics-workflows#111]
Hi

I followed the instructions in the readme but it seems like this env't variable doesn't get set or created? 

This is in the configure-deploy.sh script

> This script expects the following environment variable(s)
> ASSET_ROLE_ARN: the AWS role ARN that is used to publish assets

Which prevents the aws config file from being properly created.

Thanks
Steve

**Comment by wleepang** [comment]
The `configure-deploy.sh` script is intended for use by the CI system for automated builds and deployments. You shouldn't need to run it if you are creating your own distribution.
