### ISSUE TITLE
AWS batch with large EC2 instance types

### ISSUE THREAD

**Issue by Irsan88** [aws-samples/aws-genomics-workflows#113]
I have followed all procedures described at [the AWS docs](https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-overview/) and that works smoothly. I have used the The Genomics Workflow Core CloudFormation template with multiple parameter settings for max vCPU (I tried 100, 256, 512, 1024) but in all cases the EC2 instance types at most have 16 CPUs (max *.4xlarge instances). One of my jobs (canu) has a long running time and can be parallelized so I would like to include EC2 instance types with more CPUs than 16, how can I do that?

**Comment by ajfriedman18** [comment]
@lrsan88 you will want to modify the EC2 instances that can be found in your AWS Batch Compute Environment(s). These can be found starting at [Line 143 in the GWFCore Batch Template](https://github.com/aws-samples/aws-genomics-workflows/blob/b95b75d1a5e73f3b5727512c7e148a6aaeeb8141/src/templates/gwfcore/gwfcore-batch.template.yaml#L143).

**Comment by Irsan88** [comment]
I wasn't aware that the gwfcore-root.template.yaml makes use of nested templates like the gwfcore-batch.template.yaml. I downloaded the gwfcore-batch.template.yaml, added my preferred instance types to the list, made that file https accessible and referred to that URL in the gwfcore-root.template.yaml. That all worked, thanks!
