### ISSUE TITLE
Better error handling when provisioning Batch instance

### ISSUE THREAD

**Issue by rdavison** [aws-samples/aws-genomics-workflows#114]
In the linked issue below, we discussed a possible bug with the user data scripts.  In summary: it's likely the case that the UserData script is permitting incorrectly provisioned machines to execute jobs. Those jobs can then fail due to missing dependencies, such as `fetch_and_run.sh`. We should think about how to validate improperly provisioned machines, and how to fail them if they cannot be repaired.

For more context, see: https://github.com/broadinstitute/cromwell/issues/5872#issuecomment-730119341

**Comment by wleepang** [comment]
The UserData created by the Launch Template in the GWFcore checks if the AWS CLI is correctly installed and terminates the instance if not. One could do something similar with all required host tooling, `fetch_and_run.sh` included.

**Comment by wleepang** [comment]
Reviewing your comment from broadinstitute/cromwell#5872, here are the suggested fixes:

* fail on error for any command in UserData `runcmd`
* set `AWS_RETRY_MODE=adaptive`

**Comment by wleepang** [comment]
According to the [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html#cli-usage-retries-modes-adaptive), adaptive retries is currently experimental.

The `standard` retry mode is the default and includes exponential backoff with a default retry count of 3 and a maximum retry time of 20 seconds. Overriding the default retry count by setting `AWS_MAX_ATTEMPTS` might be sufficient.

**Comment by tthyer** [comment]
We're having the same problem intermittently. According to the batch console, our jobs are already using adaptive and 14 retries. I've added some infra to ship the cloud-init.log and cloud-init-output.log to Cloudwatch and will report back if I find anything.
