### ISSUE TITLE
Nextflow head nodes are submitted to SPOT CE by default

### ISSUE THREAD

**Issue by ajfriedman18** [aws-samples/aws-genomics-workflows#115]
Head nodes need to run without risk of spot interruption. Currently, Nextflow is submitted to the `default` job queue, which prioritizes the Spot Compute Environment over On Demand.

https://github.com/aws-samples/aws-genomics-workflows/blob/b95b75d1a5e73f3b5727512c7e148a6aaeeb8141/src/templates/nextflow/nextflow-resources.template.yaml#L226

Suggest changing to ensure the head nodes are submitted to the priority job queue (or probably even better their own queue).

**Comment by ajfriedman18** [comment]
leaving issue as is, but this may actually be with the Biotech Blueprint Nextflow Quick Start. Looking in there.

**Comment by genecentric** [comment]
I am not sure I understand this fix.
For Nextflow you submit the job directly to Batch which spins up the head node on whatever queue you ask for, preferably the priority queue that only has the on demand Compute Environment attached.  And then the Nextflow head node should submit jobs to the "Default" queue which has both the spot and on demand compute environments attached.  Then if you want jobs to run on on demand you only have to disable the spot compute environment.  Do I have this correct?  In the current version of the Batch cfn template the default queue only has the spot compute environment attached. So there would be no way to get the jobs to run on the OnDemand queue.

**Comment by wleepang** [comment]
Your understanding is correct. This issue was created when the priority queue was configured to spill over from the on-demand CE to the spot CE. The default MaxVCpus for the on-demand CE is 100. If you ran a sufficient amount of Nextflow head jobs you would start to get them placed on spot instances. The latest version of the templates removes this possibility by having the priority job queue only configured with the on-demand CE.

**Comment by genecentric** [comment]
So that's just it.  I understand removing the Spot CE from the priority queue but why is the on-demand CE removed from the Default Queue in the current version of gwfcore-batch.template.yaml?  Wouldn't I want that there in case I want my jobs to go to the on demand CE?

**Comment by wleepang** [comment]
That configuration is no longer recommended with the implementation of the `SPOT_CAPACITY_OPTIMIZED` allocation strategy for SPOT based CEs.
