### ISSUE TITLE
Files stored in /tmp are removed

### ISSUE THREAD

**Issue by tthyer** [aws-samples/aws-genomics-workflows#118]
For the cromwell resources, several important files are stored in `/tmp`. This is problematic because typically the `/tmp` dir is cleaned periodically. For example, I could not restart cromwell using the command `supervisorctl restart cromwell-server` because its socket file had been removed. I propose that all files in `cromwell-resources.template.yaml` be given a more permanent home, and will submit a PR.

**Comment by wleepang** [comment]
Should be fixed in the v3.0.5 release.
