### ISSUE TITLE
Cannot connect to Cromwell Server

### ISSUE THREAD

**Issue by tthyer** [aws-samples/aws-genomics-workflows#120]
@wleepang, with the removal of KeyName in commit d2055f4, I was not able to connect to a newly created instance of the cromwell server. I understand the reasoning behind this but when I go to the EC2 console, press Connect, and choose Session Manager, I see this message:
```
We weren't able to connect to your instance. Common reasons for this include:
1. SSM Agent isn't installed on the instance. You can install the agent on both Windows instances and Linux instances.
2. The required IAM instance profile isn't attached to the instance. You can attach a profile using AWS Systems Manager Quick Setup.
3. Session Manager setup is incomplete. For more information, see Session Manager Prerequisites.
```
(later update)
I added the AWS-provided policy AmazonSSMManagedInstanceCore to the instance profile ManagedPolicies and then was able to connect. But I think you might also want to mention that you'll be connected as ssm-user (at least by default) and you'll end up by default in `/usr/bin`, not in `/home/ec2-user`,  so maybe something should be added to the docs about this.

**Comment by wleepang** [comment]
Good catch - Merged your PR
