### ISSUE TITLE
Intermittent failure when localizing inputs

### ISSUE THREAD

**Issue by tthyer** [aws-samples/aws-genomics-workflows#124]
The purpose of this issue is to track experimental changes made to the aws-genomics-workflows environment to solve the awscli v2 copying problem discussed in [this issue](https://github.com/aws/aws-cli/issues/5876).

The error manifests as `download failed...[Errno 12] Cannot allocate memory`.

So far, the only changes I have tried are:

- running a custom cromwell jar that adds `--debug` to the s3 command
- using amazon linux 2 in the batch compute environment (it still defaults to version one) -- only so that everything is the latest version, not for a concrete reason

After this bug started to occur, I also added the following to UserData in the LaunchTemplate to solve a separate problem, and it could have a bearing on behavior:
```
                #cloud-config
                repo_update: true
                repo_upgrade: all
```

Since making these changes the problem hasn't recurred yet, but given how intermittent it has been, I am opening this issue to discuss the problem.

Next steps will be checking things like the swap available as well as the ulimit setting for the container.

**Comment by tthyer** [comment]
The change to upgrade to amazon linux 2 is to add the following to the batch compute environment(s) under ComputeResources:
```
        Ec2Configuration:
          - ImageType: ECS_AL2
```

**Comment by henriqueribeiro** [comment]
I changed it to use the AL2 but I got the same error. Does anyone have some hints in what to do next?

**Comment by kdaily** [comment]
I updated with a comment on the linked issue with some possibilities:

https://github.com/aws/aws-cli/issues/5876#issuecomment-771042979

**Comment by henriqueribeiro** [comment]
I added new info on the issue: https://github.com/aws/aws-cli/issues/5876#issuecomment-775176703

**Comment by henriqueribeiro** [comment]
As reported in https://github.com/aws/aws-cli/issues/5876#issuecomment-776682548, after adding some swap space in the EC2 instances, I didn't get the error anymore. I will work on a PR.
