### ISSUE TITLE
Private S3 bucket access

### ISSUE THREAD

**Issue by tthyer** [aws-samples/aws-genomics-workflows#133]
Cromwell Feature Suggestion:
A policy that will allow access to private S3 buckets under the user's control that may be needed. This could be a conditionally created CloudFormation resource.
Use cases:
1. Data used as inputs: after standing up the cromwell stack, I must manually add the instance role ARN as a principal on the bucket policy.
2. A bucket to pull custom jars from: when creating the cromwell stack, I have been providing the CromwellJarUrl parameter (I have compiled my own jar with a slightly modified AwsBatchJob). This causes a weird bug because the cromwell server instance is trying to pull the jar, but it doesn't have permission to pull from the bucket. It stores the "access denied" error message as the jar file, then on startup there are just messages about the jar being corrupt. 

What I'm thinking of is something like a Cloudformation parameter which is a CommaDelimitedList; create a policy which allows read and list permissions to the list of buckets, where the principal is the output of cromwell instance role. The policy would only be created if the CommaDelimitedList were not empty (use a CFN condition to check that).

**Comment by henriqueribeiro** [comment]
This is indeed a good feature. I just did a PR (https://github.com/aws-samples/aws-genomics-workflows/pull/143). Hope it copes with what you proposed @tthyer
