### ISSUE TITLE
ContainerBuildNextflow fails after Stack deletion

### ISSUE THREAD

**Issue by brooksomics** [aws-samples/aws-genomics-workflows#134]
I've been using the gwfcore Stack successfully for about a month with Nextflow. 

Recently, I needed to delete the [VPC, gwfcore, and Nextflow Stacks](https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/) and rebuild. I can rebuild the first two successfully using the same code, but the NF code fails with:
```
Failed to create resource. Code Build job 'CodeBuildProject-jE5ESVV5lqzx:c02a5db6-1ca8-4635-a7e9-14cd888362cc' in project 'CodeBuildProject-jE5ESVV5lqzx' exited with a build status of 'FAILED'.
```
I think this is happening at the [CustomeCodeBuildInvocation](https://github.com/aws-samples/aws-genomics-workflows/blob/a614fed525710135f0949a88efe059c5b940810f/src/templates/_common/container-build.template.yaml#L270-L274) step. In ECR, the `nextflow` repository is created, but no image is pushed. 

I noticed few lines below this you have a [comment in your code indicating CloudFormation doesn't support deleted ECR Images](https://github.com/aws-samples/aws-genomics-workflows/blob/a614fed525710135f0949a88efe059c5b940810f/src/templates/_common/container-build.template.yaml#L290-L321)? Is there a way for me to use `nextflow-resources.template.yaml` now that I've deleted the `nextflow` ECR? I've tried moving this architecture to a new bucket, with no luck. Perhaps moving it to another Availability Zone would work (?) but that introduces other problems for me if that's the only solution!

**Comment by jennomics** [comment]
How recently did you attempt this? As part of an ongoing effort to remove
non inclusive language at AWS, we have changed “master” to “main” in our
CodeCommit repositories. There are some templates in this repo that have
yet to be updated, although they should be very soon. This change took
effect one week ago, last Thursday.

So, wanted to rule this out before you get too far down a rabbit hole. I
will update here when we cut a new release.

**Comment by brooksomics** [comment]
I'm using the Feb 10 v.3.0.4 [release](https://github.com/aws-samples/aws-genomics-workflows/archive/v3.0.4.zip), so the `main` language isn't in the codebase that I can see.

**Comment by brooksomics** [comment]
I tried switching everything to a different Availability Zone and am getting the same error:
```
nextflow-resources-ohio-ContainerBuildNextflow-1MBVF42MUW9YJ` `Failed to create resource. Code Build job 'CodeBuildProject-AE5aKiToaz5V:9fe12202-b41c-40f4-878b-af5573c46905' in project 'CodeBuildProject-AE5aKiToaz5V' exited with a build status of 'FAILED'.
```
Can you confirm you are able to delete in your environment and rebuild? I'm wondering if this is specific to my account or a more general issue with these templates and how they are building the Nextflow container?

Another thought, but I think it's unlikely the cause, are there any unique name clashes? This, generic, warning appears before launching. I can't think of anything that would collide, but thought it worth mentioning:
```
This template contains Identity and Access Management (IAM) resources. Check that you want to create each of these resources and that they have the minimum required permissions. In addition, they have custom names. Check that the custom names are unique within your AWS account.
```

**Comment by wleepang** [comment]
Should be resolved in the latest release. Feel free to reopen this issue if it is still occurring.

**Comment by brooksomics** [comment]
Unfortunately, I'm getting the same [error](https://github.com/aws-samples/aws-genomics-workflows/issues/134#issuecomment-797729696).

Have others been able to delete their Stack and rebuild using these templates? Perhaps this is suggesting a configuration issue on my end? The only modification I've made to the v3.0.5 files is changing the IntanceTypes to `- optimal`.

**Comment by jennomics** [comment]
I am also unable to deploy.

**Comment by brooksomics** [comment]
Working here too. Thanks!

**Comment by wleepang** [comment]
Great!
