### ISSUE TITLE
AWS Tibanna/Snakemake Orchestration

### ISSUE THREAD

**Issue by skchronicles** [aws-samples/aws-genomics-workflows#139]
## Adding Snakemake Documentation

Hello there,

I would like to preface this by saying thank you for creating this documentation. It is extremely useful!

I am not super familiar with this project's roadmap, but do have any future plans for including [Tibanna/Snakemake](https://snakemake.readthedocs.io/en/stable/executing/cloud.html#executing-a-snakemake-workflow-via-tibanna-on-amazon-web-services) in your workflow orchestration documentation. I am just curious as I feel like Snakemake is heavily used within the Bioinformatics community (maybe even more so than WDL/Cromwell due to its ease of use).  

Please let me know what you think,
@skchronicles

**Comment by wleepang** [comment]
Thanks for the suggestion! It's not specifically on the roadmap, but Tibanna and Snakemake are both things we've increased interest in. If both could work with AWS Batch, and by proxy the `gwfcore` described here, they would be straightforward additions.
