### ISSUE TITLE
AWS ECS ERROR: Essential container in task exited

### ISSUE THREAD

**Issue by altunhi** [aws-samples/aws-genomics-workflows#142]
Cloudformation Stacks are taken from this documentation:
https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-overview/

Called /api/workflows/ POST method with test.wdl over Cromwell REST API.
test.wdl file attached:
[test.zip](https://github.com/aws-samples/aws-genomics-workflows/files/6156503/test.zip)

AWS Batch log contains only one line:
/bin/bash: /var/scratch/fetch_and_run.sh: Is a directory

Container started from AWS Batch was stopped. ECS task log here:
{
    "tasks": [
        {
            "containers": [
                {
                    "name": "default",
                    "image": "quay.io/biocontainers/mulled-v2-ad317f19f5881324e963f6a6d464d696a2825ab6:c59b7a73c87a9fe81737d5d628e10a3b5807f453-0",
                    "lastStatus": "STOPPED",
                    "exitCode": 126,
                    "networkBindings": [],
                    "networkInterfaces": [],
                    "healthStatus": "UNKNOWN",
                    "cpu": "0",
                    "memory": "1"
                }
            ],
            "cpu": "8192",
            "healthStatus": "UNKNOWN",
            "lastStatus": "STOPPED",
            "launchType": "EC2",
            "memory": "65536",
            "overrides": {
                "containerOverrides": [
                    {
                        "name": "default",
                        "command": [
                            "/bin/bash",
                            "-c",
                            "/var/scratch/fetch_and_run.sh"
                        ],
                        "environment": [
                            {
                                "name": "AWS_BATCH_JOB_ID",
                                "value": "1ed42e67-80a8-407a-909d-8956f1e30362"
                            },
                            {
                                "name": "AWS_BATCH_JQ_NAME",
                                "value": "default-gwfcore"
                            },
                            {
                                "name": "AWS_BATCH_CE_NAME",
                                "value": "spot-gwfcore"
                            },
                            {
                                "name": "AWS_BATCH_JOB_ATTEMPT",
                                "value": "1"
                            },
                            {
                                "name": "BATCH_FILE_S3_URL",
                                "value": "../1f8935f1f88b2f0ba481f1f4a9da5cfa"
                            },
                            {
                                "name": "BATCH_FILE_TYPE",
                                "value": "script"
                            }
                        ],
                        "cpu": 8192,
                        "memory": 65536,
                        "resourceRequirements": []
                    }
                ],
                "inferenceAcceleratorOverrides": []
            },
            "pullStartedAt": "2021-03-17T13:32:26.337000+03:00",
            "pullStoppedAt": "2021-03-17T13:32:33.756000+03:00",
            "startedAt": "2021-03-17T13:32:34.319000+03:00",
            "stopCode": "EssentialContainerExited",
            "stoppedAt": "2021-03-17T13:32:34.577000+03:00",
            "stoppedReason": "Essential container in task exited",
            "stoppingAt": "2021-03-17T13:32:34.577000+03:00",
            "tags": [],
            "version": 3
        }
    ],
    "failures": []
}

**Comment by wleepang** [comment]
@altunhi - This typically happens when the underlying instance is not provisioned correctly - i.e. the `fetch_and_run.sh` script was not copied to the right location.

A patch to address this is in the works. In the meantime you could add some logic to the [ecs-additions-common.sh](https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/ecs-additions/ecs-additions-common.sh) script in the CodeCommit repo that is created to terminate the instance on any provisioning errors.

**Comment by wleepang** [comment]
related to #114

**Comment by altunhi** [comment]
Hi @wleepang, 
Thanks for your response.. I think cloudformation stack files in [this](https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-overview/) documentation arent up to date. I tried using stack files in the github repo. I have created own distrubution on S3. I have encountered an another error.

2021-03-26 15:01:07,426 cromwell-system-akka.dispatchers.engine-dispatcher-24 INFO  - Assigned new job execution tokens to the following groups: cbe78e1e: 1

2021-03-26 15:01:09,334 cromwell-system-akka.dispatchers.engine-dispatcher-23 INFO  - cbe78e1e-b675-4fa1-a806-90c086e49fc3-EngineJobExecutionActor-RunWholePipeline.Bwamem:NA:1 [UUID(cbe78e1e)]: Could not copy a suitable cache hit for cbe78e1e:RunWholePipeline.Bwamem:-1:1. No copy attempts were made.

The job was stated as runnable, wasn't started on Batch Dashboard. No EC2 instance was provisioned for running job.

**Comment by jennomics** [comment]
"cpu": 8192,
"memory": 65536,

**Comment by wleepang** [comment]
Sharp eye @jennomics 

@altunhi - the resources being requested do not match any available instance types - i.e. you've requested an instance with 8192 cpus. Could that be an error in the WDL submitted?

**Comment by altunhi** [comment]
Yes, right. I changed this definition then worklow was worked fine. 
Thanks @jennomics @wleepang

For those who have the same problem, I would recommend the github repo rather than documentation when using cloudformation stacks.

**Comment by wleepang** [comment]
@altunhi - Thanks for the feedback. The documentation is kept in sync with tagged releases from this repo. Releases can be considered stable enough for general use. Code on the main branch of the repo is considered "staged for testing" for the next release.
