### ISSUE TITLE
Add ability to add custom configs to nextflow build

### ISSUE THREAD

**Issue by GHAStVHenry** [aws-samples/aws-genomics-workflows#145]
My pipelines exist in a self-hosted GitLab server...

`nextflow run` does cannot resolve the https location unless a [scm file](https://www.nextflow.io/docs/latest/sharing.html#scm-configuration-file) with a custom provider is present

I am aware I can fork your repo and customize the Dockerfile for nextflow container building so that it is included... but it would be convenient if custom configs like scm could be a cloudformation input that copies the file into the container!?!?!

**Comment by genecentric** [comment]
I found a good solution was to modify the nextflow.aws.sh and copy the scm file from s3 like this 
"aws s3 cp $NXF_SCM .nextflow/scm"

specifying the bucket location as an environment variable that can be set when submitting the initial head node batch job.
aws batch submit-job --job-name nf-hello --job-queue arn:aws:batch:us-east-1:xxxxxxxxx:job-queue/batchqueue --job-definition nextflow-test3 --container-overrides environment='{name="NXF_SCM",value="s3://bucket/scm"}',command="gitlaburl/path"

This keeps me from being tied to a certain bucket or scm file as it can be specified on job submission.

**Comment by GHAStVHenry** [comment]
That sounds like a reasonable solution!
