### ISSUE TITLE
Input path not working

### ISSUE THREAD

**Issue by GHAStVHenry** [aws-samples/aws-genomics-workflows#146]
Process in .nf has the following input:
`path experimentSettings, stageAs: "ExperimentSettings.csv" from experimentSettingsMeta`

the job for that process submits to batch, but doesn't start properly  and has the error:
```
Command wrapper:
  nxf-scratch-dir ip-172-31-13-31.ec2.internal:/tmp/nxf.FtGiOtP5cD
  
  Unknown options: Settings.csv
  
  Unknown options: ExperimentSettings.csv
```

there are no error logs for the process but .command.run includes this for staging:
```
nxf_stage() {
    true
    # stage input files
    downloads=()
    rm -f parse_meta.py
    rm -f File.csv
    rm -f ExperimentSettings.csv
    rm -f Experiment.csv
    rm -f Q-Y5F6_10K.R1.fastq.gz
    rm -f Q-Y5F6_10K.R2.fastq.gz
    rm -f .command.sh
    rm -f .command.run
    downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/stage/84/51c0f5a73bca1a1a68dc914779b193/parse_meta.py parse_meta.py")
    downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/06/5b20bc89a19f9d57dfa1deca02a736/Q-Y5F6_inputBag/data/File.csv File.csv")
    downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/06/5b20bc89a19f9d57dfa1deca02a736/Q-Y5F6_inputBag/data/Experiment\ Settings.csv ExperimentSettings.csv")
    downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/06/5b20bc89a19f9d57dfa1deca02a736/Q-Y5F6_inputBag/data/Experiment.csv Experiment.csv")
    downloads+=("nxf_s3_download s3://bicf-output/ci-env/input/Q-Y5F6_10K.R1.fastq.gz Q-Y5F6_10K.R1.fastq.gz")
    downloads+=("nxf_s3_download s3://bicf-output/ci-env/input/Q-Y5F6_10K.R2.fastq.gz Q-Y5F6_10K.R2.fastq.gz")
    downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/0b/685573f90268f8f3bfdce5caf83787/.command.sh .command.sh")
    downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/0b/685573f90268f8f3bfdce5caf83787/.command.run .command.run")
    nxf_parallel "${downloads[@]}"
}
```

I think the error is happening here: `downloads+=("nxf_s3_download s3://bicf-output/_nextflow/runs/06/5b20bc89a19f9d57dfa1deca02a736/Q-Y5F6_inputBag/data/Experiment\ Settings.csv ExperimentSettings.csv")`

the file `s3://bicf-output/_nextflow/runs/06/5b20bc89a19f9d57dfa1deca02a736/Q-Y5F6_inputBag/data/Experiment\ Settings.csv` does exist in the bucket

any thoughts?

ps: I change the name of the file in the outputting process to not have the space and it now works...

**Comment by wleepang** [comment]
I'm not sure what `nxf_s3_download` does, but I'd speculate that it is not handling spaces correctly when/if it calls `aws s3 cp`. If you can remove the spaces from the file name in the S3 URI, I'd suggest that route. Otherwise, this seems like a bug to bring up with [nextflow](https://github.com/nextflow-io/nextflow).

**Comment by wleepang** [comment]
It's possible this could be the root cause:
https://github.com/nextflow-io/nextflow/blob/914d7cb40bf58ff977717cd137352e7dfe97dbdb/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/S3Helper.groovy#L54

Suggest posting a issue there.

**Comment by nathanthorpe** [comment]
Did you ever get this resolved? 

I've been having the same issue but it works fine when I run the command.run file locally and it seems to run on their integration tests. I think it may have to do with how the environment is setup?

**Comment by nathanthorpe** [comment]
I just created a PR to fix this issue.
