### ISSUE TITLE
Add EFS support for shared data

### ISSUE THREAD

**Issue by ajfriedman18** [aws-samples/aws-genomics-workflows#161]
I have been working with a few customers (WGS and metagenomics) who have shared data they want to access across their nodes. While in some cases it is cheaper/preferable to download these data as part of a launch template modification, adding the ability for them to use EFS is preferable for some, particularly in the metagenomics space as reference genomes can be large and there's a heavy reliance on annotation databases.

We have this working for one customer, but before I tidy it up and add in the PR, wanted to make sure that we hammer out what would be included in the PR. What I'm thinking is:
1. An optional parameter specified as part of `gwfcore-root` that gives the user the option to mount an EFS file system
2. Conditional resource creation within `gwfcore-root` (also happy to have it as a nested stack) that creates the FS with the requisite security groups and mount targets
3. Modification of the `gwfcore-launch-template` to add the EFS mount to the UserData
4. Modify Nextflow default config generation

I recognize that different workflow engines will have different ways of representing FS mounts, particularly if they are managing the creation of AWS Batch Job Definitions. For example, in Nextflow you would modify https://github.com/aws-samples/aws-genomics-workflows/blob/043728e0f2a8cbb9342a662d708380efdd1d833c/src/containers/nextflow/nextflow.aws.sh#L43-L48 to accept EFS.

Right now, my customers are using Nextflow, so that is my priority. However, wanted to understand if support for other engines is required at this point as I'm cognizant of maintaining feature parity when possible.

**Comment by wleepang** [comment]
I'm open to all of the above. I don't see lock step feature parity across engines as a requirement. If Nextflow customers need this now, it's worth integrating and then bringing the other engines up to speed in due course.

**Comment by ajfriedman18** [comment]
Good deal. I'll spend some time working on this in next week or two

**Comment by brooksomics** [comment]
I'm starting to use larger reference genomes and am running into disc storage issues, so I thought I'd try an EFS mount.

Using the latest [commit](https://github.com/aws-samples/aws-genomics-workflows/commit/2f9678227b8929a27b8db488ba6076c8f62bb215), I rebuilt my Stack and am met with:
```
[null] NOTE: Can't stage file file:///mnt/efs/genomes/big_ref/bwa_mem2_index -- file does not exist -- Execution is retried (1)
```
This code works when using s3 as the input in NextFlow:
```
input:
file assembly_in from file("s3://efs_copy/genomes/big_ref/bwa_mem2_index/", type: 'dir')
```
But produces the above error using EFS:
```
input:
file assembly_in from file("/mnt/efs/genomes/big_ref/bwa_mem2_index/", type: 'dir')
```

On the head node, everything in the [Container details](https://github.com/aws-samples/aws-genomics-workflows/blob/2f9678227b8929a27b8db488ba6076c8f62bb215/src/templates/nextflow/nextflow-resources.template.yaml#L226) look correct, including the path `/mnt/efs/`.

My questions:
1. Child nodes, however, do not have `/mnt/efs` in their `Environment variables configuration` section. Is this expected?
2. If so, how can child nodes access the mount point if only mounted to the head node? Said another way, why does the head node, i.e. the orchestration node, have the mount point - shouldn't the children nodes, i.e. the ones doing the compute, have access?

I think I may be missing something fundamental here. Any guidance? Thanks!

**Comment by ajfriedman18** [comment]
@brooksomics sorry to hear there's an issue. Have a couple questions to start:

1. Wanted to first confirm you have the data already staged on your EFS file system.
2. If so, if you SSH into your Nextflow Head Node (use AWS Systems Manager connection), what do you get when you do `ls /mnt/efs/genomes/big_ref/`
3. If it's there on the head node, what happens if you run the same command on a child node?

**Comment by brooksomics** [comment]
Thanks for the speedy reply! 

1. Yes and this EFS is mounted on most of our onDemand EC2 without issue, but this is the first time I've tried to use an EFS with NextFlow, let alone EFS with NextFlow on Batch. A potential issue I thought of is that our EFS is in a different VPC subnet relative to the VPC I set up using [AWS's template](https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview.html).
2. I've never used AWS System Manager, nice! I was curious how I was supposed to SSH into an EC2 without a public IP. On both the head and child node, `/mnt/efs/` exist, but `efs/` is empty. So maybe the VPC is the issue here?
3. Answered in (2.) above.

**Comment by markjschreiber** [comment]
@brooksomics re point 1, is the EFS volume in the same VPC as your batch environment? If not then you'd need to allow network traffic between the two VPCs via peering or similar approach. If it is in the same VPC then being in a different subnet shouldn't be an issue as long as the VPC configuration allows communication between the subnets. With EFS you can also create access points in multiple subnets. It would also be worth checking the security groups of the AWS Batch EC2 instances and the access points to ensure the ports required for EFS traffic are accessible. 

Once any network issues are resolved and the volume is visible on the Batch EC2s you will need to ensure that the Job Definitions of both the Nextflow head job and any workflow task jobs mount the volume into the container as by default all docker containers are isolated from their hosts volumes. 

Once everything is connected it's worth keeping an eye on the EFS metrics (visible in the AWS console) to ensure that your workflow doesn't overwhelm the throughput of the volume. This can easily happen when a workflow has many parallel steps reading (or writing) large files at the same time. If this happens you may need to edit the EFS configuration to make use of provisioned IO.

**Comment by brooksomics** [comment]
Hi @markjschreiber , my EFS is in a separate VPC from my NextFlow Stack and there's no peering configured, so I think that's likely the issue. I'll reconfigure later this week and let you know how it goes. Thanks!
