### ISSUE TITLE
Nextflow image not avaliable in public.ecr.aws

### ISSUE THREAD

**Issue by wojukasz** [aws-samples/aws-genomics-workflows#171]
This issue is actually experienced when working with https://github.com/aws-quickstart/quickstart-nextflow but I traced it to this repo.

During provisioning of nextflow components, the  CFN stacks fail during nextflow image codebuild step, this is caused by nextflow image being wrongly referenced under ` public.ecr.aws/seqera-labs/nextflow`.
However, the container can be pulled from the official nextflow repository on docker, or alternatively is available under another name in ECR: https://gallery.ecr.aws/seqera-labs/nextflow

Temprorary fix is to switch:
`FROM public.ecr.aws/seqera-labs/nextflow:${VERSION} AS build`
to
`FROM nextflow/nextflow:${VERSION} AS build` or `FROM public.ecr.aws/seqera-labs/nextflow:21.06.0-edge AS build`
on line: [2 in nextflow Dockerfile definition](https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/containers/nextflow/Dockerfile#L2) and rerun the build.

I have tested this and CodeBuild completed it successfully.

PR: https://github.com/aws-samples/aws-genomics-workflows/pull/172

**Comment by wleepang** [comment]
The primary issue is that the `latest` tag is no longer available for the image in ECR Public. It will work if you specify a version (e.g. `20.10.0`) when launching the nextflow-resources template.

**Comment by wojukasz** [comment]
This will still fail unless the user uses the full tag, which needs to include `-edge` beside the image version.

To make it work we have to use (for example) `21.06.0-edge` as `${VERSION}` in CFN template.

**Comment by wleepang** [comment]
`latest` and stable (e.g. non-edge) versions of nextflow are now in ECR public
