### ISSUE TITLE
CodeBuild step of Nextflow resources stack fails

### ISSUE THREAD

**Issue by jennomics** [aws-samples/aws-genomics-workflows#175]
The default is to use the latest tag for the Nextflow container, but that's no longer being used. Recommend to check https://gallery.ecr.aws/seqera-labs/nextflow for the latest version to include when deploying the Cloud Formation template. Otherwise, build fails without informative error.

**Comment by wleepang** [comment]
the `latest` tag is now available for the Nextflow image in ECR Public Gallery
