### ISSUE TITLE
Incorrect fetch_and_run.sh

### ISSUE THREAD

**Issue by hsimran13** [aws-samples/aws-genomics-workflows#178]
Hello,

We are following the online steps to deploy an AWS Batch environment using cloudformation in our AWS account and running a simple hello world example.  Our workflow fails with a message saying that it cannot read s3://bucket_name/cromwell-execution/wf_hello/a707c2f3-a513-4299-9912-16408a8f4ddf/call-hello/hello-rc.txt.  The reason it cannot read this file is because it does not exist.  In looking at the full workflow, I realized that the /usr/local/bin/fetch_and_run.sh path is being mapped into the container image that we are using and that is what is being executed.  However, when I looked at the ECS worker node, I saw that this was created as an empty directory:

[root@sgdcmls114-usw2 ~]# ls -l /usr/local/bin/
total 4
drwxr-xr-x 2 root root 4096 Sep 27 22:34 fetch_and_run.sh

That definitely seems wrong.  Does anyone know where in CloudFormation or other steps is this fetch_and_run.sh script created?  I tried a sample fetch_and_run.sh script and it got a little further but still failed since the container image did not have the unzip binary installed.  Can someone please help provide more information regarding this fetch_and_run.sh script and where this comes from and what should it look like?

Thanks,
-Simran

**Comment by markjschreiber** [comment]
Hi,

The error you describe can happen when the ec2 node fails to download the `fetch_and_run.sh` script. I can be a transient error, so the workflow may work on the next attempt. However, if you are observing the error consistently then it may indicate some other problem. Can you tell us more about the context in which this happened? Information such as the workflow engine (Cromwell, Nextflow, etc) and the type of workflow you were running including information such as the step of the workflow that failed and if the failure was during a scatter step.

The content of the script itself can be found at https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/ecs-additions/fetch_and_run.sh
