### ISSUE TITLE
Accessing private github repos from Nextflow

### ISSUE THREAD

**Issue by nathan-wan** [aws-samples/aws-genomics-workflows#184]
Hi

We're interested in providing github credentials to access our private repos with the gwf stack. One way to do it would be provide the credentials in a [.nextflow/scm](https://www.nextflow.io/docs/latest/sharing.html#scm-configuration-file) file, but that would need to be put onto the image somehow. What is the current recommended method for that with gwfcore? Thanks!

Nathan

**Comment by wleepang** [comment]
I suggest customizing the nextflow container and AWS Batch job definition to pull secrets from [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/). See: https://docs.aws.amazon.com/batch/latest/userguide/specifying-sensitive-data-secrets.html
