### ISSUE TITLE
Multiple Cromwell subworkflows run on the same Batch EC2 instance

### ISSUE THREAD

**Issue by yihming** [aws-samples/aws-genomics-workflows#188]
Hello,

I have a [Cellranger workflow](https://github.com/lilab-bcb/cumulus/blob/master/workflows/cellranger/cellranger_workflow.wdl) which could trigger multiple Cellranger count subworkflows running in parallel.

However, I encounter an issue that, say I have 4 samples to run cellranger count, if I run them one after another sequentially on AWS, they all finish successfully. But if I directly use my workflow to trigger 4 cellranger count subworkflows **in parallel**, they all fail in the middle of the execution.

To inspect the issue, I tracked the EC2 instance list, and saw that only 2 EC2 instances were created, with 3 subworkflows (i.e. 3 docker containters) running on one, while 1 subworkflow running on the other. Moreover, the 3 docker containers used the shared EBS volume mount at "/var/lib/docker". See the attached screenshot below for the info of the Batch instance running the 3 subworkflows:

![Screen Shot 2022-03-28 at 22 36 10](https://user-images.githubusercontent.com/2455754/160521680-995a1b71-ab2f-4e3a-88e3-5a106de4be41.png)

This causes troubles that led to Cellranger count failure. On Google Cloud, there would be 4 different VM instances created dedicated for the 4 subworkflows, respectively. So I'm wondering if it is possible to switch to such configuration in aws-genomics-workflows architecture, and if so, how I should modify the source code.

Many thanks!

Sincerely,
Yiming

**Comment by markjschreiber** [comment]
Hi Yiming,

The engines that AGC deploy use AWS Batch to run the tasks of the workflow and Batch uses a bin-packing algorithm to place containers onto instances meaning that it is possible that multiple containers will end up on one host. We are investigating ways to make containers single tenant although it will require changes to the engines or their AWS Batch adapters. Depending on the type of error that occurred there may be other strategies you could use in the meantime. Could you send details of the actual error? The `agc logs engine` and `agc logs workflow` commands should help.

**Comment by yihming** [comment]
Three things to add for my issue:
* I tried both spot instances and on-demand instances, and they both failed with the same error messages at `cellranger count` step.
* The instance resources are sufficient. For example, on the instance shown in the screenshot above, 3 subjobs were hosted. Each job specified to use 32 vCPUs and 120 GB memory, and the instance did have 96 vCPUs and over 360 GB memory assigned. Thus, the instance type limitation is probably not the failure reason. 
* I used a hardened ECS-optimized AMI generated by the Cloud team in my company. To check if it is the AMI that caused the issue, I also tried the official Amazon ECS-optimized AMI (ami-0814780bdc1490485) by following [this list](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) and copying the AMI available for `us-west-2` region into my account. However, I still saw the same failure.

**Comment by wleepang** [comment]
Is it possible to get the contents of this log?
```

[error] Pipestance failed. Error log at:

results/SC_RNA_COUNTER_CS/SC_MULTI_CORE/MULTI_GEM_WELL_PROCESSOR/COUNT_GEM_WELL_PROCESSOR/_BASIC_SC_RNA_COUNTER/_MATRIX_COMPUTER/ALIGN_AND_COUNT/fork0/chnk11-u03b9423bc3/_errors
```

One other thing you can do is set the largest instance type in the compute environment you are using to ones that have exactly the number of vCPUs and memory this specific task needs (assuming it is the largest one in the workflow). This is a way to force AWS Batch to only place only one of these jobs per instance.

**Comment by yihming** [comment]
@wleepang 

Thanks for taking care of my case!

The content of the log file is
```
Job failed in stage code



signal: killed
```
which was already included in the STDOUT file.

You suggestion is exactly what I discussed with Mark in the meeting. I'll keep both of you posted about my trial's result.


Sincerely,
Yiming

**Comment by yihming** [comment]
@markjschreiber @wleepang Just update that after restricting instance types to only allow <=32 vCPUs, we were able to go around the cellranger count IO issue by enforcing one task per instance.

Although it's not an ideal solution, it at least works.

I'll close this issue. And thank you for your help!

**Comment by yihming** [comment]
Just a follow-up update:

I recently raised the ulimits thresolds of docker in our AWS deployment by following the discussion at https://github.com/aws/amazon-genomics-cli/issues/45.

This kind-of solves our issue here:

* The previously failed jobs now succeed.
* However, those jobs stacked in one common EC2 instance take longer time. This is because they take longer time to finish the cellranger count step (i.e. `ALIGN_AND_COUNT`), which is exactly the step previously causing the failure without raising ulimits threshold.
