### ISSUE TITLE
AWS does not allow `File? f = "filename.txt"` in WDL task output section

### ISSUE THREAD

**Issue by yihming** [aws-samples/aws-genomics-workflows#194]
Hello,

I have the following kind of code in my WDL version 1.0 task:
```
version 1.0
...
task some_task {
    ...
    command {
        ...
        python <<CODE
        if some_condition:
            with open("file.txt", 'w') as fout:
                fout.write("some content\n")
        CODE
    }

    output {
        File? output_file = "file.txt"
    }
}
```

When running with Google Cloud, it has `output_file` returned if `some_condition` is satisfied, while `output_file = null` otherwise.

However, when running on AWS Batch, it failed with the following error message:
```
The user-provided path /tmp/scratch/file.txt does not exist.
```

I checked OpenWDL documentation, and found:
* [Version 1.0](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md) doesn't have any example code as above.
* Starting from [Version 1.1](https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#task-outputs), there is such an example code.

However, I still don't quite understand the inconsistency of Cromwell's behavior on this feature between GCP and AWS, as I explicitly stated `version 1.0` on the top of my WDL file.

Could you please help me understand the logic of how AGC deals with this case? Thanks!

Sincerely,
Yiming

**Comment by markjschreiber** [comment]
Optional outputs are officially a feature of WDL 1.1 which requires a later version of Cromwell. Technically it shouldn't validate with 1.0 but I guess Cromwell in GCP is tolerant of it?

**Comment by markjschreiber** [comment]
You might also be able to use the recently published solution that uses Loka's fork of Cromwell integrated with the amazon-genomics-workflow templates. https://aws.amazon.com/blogs/industries/using-structural-variant-analysis-on-aws-with-amazon-fsx-for-lustre-in-novel-therapeutic-discovery/?nc1=b_rp

This is based on a more recent version of Cromwell that I believe supports WDL 1.1 and also allows Cromwell to make use of data from FSx for Lustre which will allow much higher IO throughput.

**Comment by yihming** [comment]
Thank you very much for your clarification and information!

Just to confirm, is the AWS-customized Cromwell released here: https://github.com/henriqueribeiro/cromwell/releases? Thanks!

**Comment by markjschreiber** [comment]
Yes, that is the one

**Comment by yihming** [comment]
Thanks! I'll try it.
