### ISSUE TITLE
m5n instances not available in us-west1

### ISSUE THREAD

**Issue by ksebby** [aws-samples/aws-genomics-workflows#196]
I get the following error when using cloud formation with[ src/templates/gwfcore/gwfcore-root.template.yaml](https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/gwfcore/gwfcore-root.template.yaml).

`
1 validation error detected: Value 'Error executing request, Exception : Instance type can only be one of [r3, r4, m6g.xlarge, m6i.xlarge, r5, optimal, r5d.24xlarge, m3.xlarge, r4.16xlarge, r5a.2xlarge, c6g.4xlarge, m6gd.xlarge, m5.xlarge, c5a.2xlarge, r6g.4xlarge, r6g.16xlarge, i3.4xlarge, z1d.3xlarge, c6gd.12xlarge, m5.large, c5d.large, m6g.2xlarge, m6g, m6i, c5.large, g4dn.2xlarge, c5.metal, i3en.6xlarge, inf1.2xlarge, m6i.4xlarge, r6gd.4xlarge, m5.2xlarge, r6g.xlarge, c3, c4, c5, m6gd, m6gd.12xlarge, m6g.8xlarge, r5n.16xlarge, c5a.8xlarge, i2.xlarge, m5d.12xlarge, m5.metal, c5d.metal, m4.4xlarge, m5.12xlarge, inf1, m6i.large, m6g.12xlarge, m6gd.4xlarge, r5n.4xlarge, c4.large, c5d.2xlarge, z1d, d2, r5d.2xlarge, r5.xlarge, c4.4xlarge, c4.xlarge, c6g.large, r6gd.12xlarge, c6gd.medium, r4.8xlarge, m5d.xlarge, c6gd.2xlarge, m5.8xlarge, c5.2xlarge, g3.8xlarge, c5n.9xlarge, c5n.2xlarge, m6i.24xlarge, r4.2xlarge, m5zn.6xlarge, m5zn.12xlarge, m5d.4xlarge, c6g.metal, c5a, m6i.12xlarge, c5d, c5d.xlarge, r5ad.xlarge, r5a.8xlarge, c5a.16xlarge, c5n, c6gd, r3.4xlarge, c6g.12xlarge, c5.12xlarge, r5d.xlarge, m6gd.large, m6g.large, m6i.8xlarge, f1, i3en.xlarge, c6gd.xlarge, r5n.2xlarge, c6g, r6gd.2xlarge, r5n.12xlarge, m5a.4xlarge, c5n.metal, c5.xlarge, c5n.4xlarge, g2, m5d.24xlarge, g3, m5zn, c5.9xlarge, r5d.8xlarge, d2.2xlarge, c6gd.16xlarge, r5.2xlarge, i3en.2xlarge, r5ad.2xlarge, f1.2xlarge, r5a, r5d, m6gd.16xlarge, i2.8xlarge, z1d.12xlarge, m6g.metal, r3.xlarge, r5n, m5.24xlarge, g4dn.12xlarge, c6g.2xlarge, r5d.12xlarge, z1d.xlarge, m3.2xlarge, i3en.24xlarge, m5ad.8xlarge, i3en.3xlarge, c5d.12xlarge, r5a.12xlarge, r5a.4xlarge, i3.large, c6gd.large, m3.medium, c5a.12xlarge, r6g, c5n.xlarge, r5ad.16xlarge, i3.metal, c6gd.metal, i3.16xlarge, r6g.12xlarge, c5n.large, m4.16xlarge, i2, i3, c3.2xlarge, r5.24xlarge, m6i.16xlarge, c6g.xlarge, f1.4xlarge, r5.4xlarge, m6gd.8xlarge, m6gd.metal, g3.4xlarge, r3.8xlarge, m5d.8xlarge, c5a.xlarge, c5a.large, m5ad.12xlarge, r5ad.large, m4.xlarge, c6gd.4xlarge, g2.2xlarge, c3.4xlarge, r5ad.12xlarge, c4.2xlarge, g2.8xlarge, m5a.24xlarge, c6g.16xlarge, r5.large, z1d.large, r3.2xlarge, m5d.2xlarge, f1.16xlarge, m5zn.large, i3en, m6gd.medium, g4dn.4xlarge, r5d.4xlarge, c5d.24xlarge, r5d.metal, m6g.medium, g4dn.xlarge, m5ad.xlarge, r6g.medium, c4.8xlarge, m5a.8xlarge, c5d.9xlarge, m5ad.4xlarge, g3s, r6g.large, r5ad.4xlarge, m5ad.24xlarge, r5ad, c5.24xlarge, r5.16xlarge, g4dn.metal, r4.xlarge, m5a.2xlarge, m5ad.large, i3en.metal, r6g.2xlarge, m5d.16xlarge, m5a.xlarge, m5zn.xlarge, i3.2xlarge, r5ad.24xlarge, m3, r6g.8xlarge, m4, r6gd.xlarge, m5, r5d.large, z1d.6xlarge, m5a.12xlarge, c3.large, i2.4xlarge, m5zn.metal, z1d.metal, inf1.24xlarge, i3.xlarge, d2.4xlarge, r5a.16xlarge, m5.16xlarge, c6g.medium, i3en.large, m5d.large, r5a.xlarge, r5.8xlarge, m4.10xlarge, c5.4xlarge, r5a.24xlarge, i3.8xlarge, c6g.8xlarge, m4.2xlarge, inf1.6xlarge, m5zn.2xlarge, d2.xlarge, m5a.large, d2.8xlarge, c5n.18xlarge, m6g.4xlarge, r5n.xlarge, r6gd.large, g3.16xlarge, c5.18xlarge, c6gd.8xlarge, m6g.16xlarge, r4.4xlarge, i3en.12xlarge, g4dn.16xlarge, r5d.16xlarge, m4.large, r6gd.8xlarge, m5ad, g4dn.8xlarge, r5n.24xlarge, i2.2xlarge, r5.metal, c5d.18xlarge, c5a.4xlarge, m5d.metal, r3.large, m5ad.2xlarge, z1d.2xlarge, r5ad.8xlarge, r6gd.medium, g3s.xlarge, r6gd, m5a.16xlarge, c3.xlarge, g4dn, r6gd.metal, r5.12xlarge, m6i.2xlarge, r4.large, c5a.24xlarge, m3.large, m5ad.16xlarge, r6gd.16xlarge, r5n.8xlarge, m6i.32xlarge, m6gd.2xlarge, m5a, m5zn.3xlarge, r5a.large, c5d.4xlarge, r5n.large, c3.8xlarge, inf1.xlarge, m5d, m5.4xlarge], RequestId: ef917b37-4334-474c-968e-10c4453fedac (Service: Batch, Status Code: 400, Request ID: ef917b37-4334-474c-968e-10c4453fedac)' at 'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024
`

I am working in us-west-1 and the m5n instances are not available there and are the cause of this error (removing them creates the stack without issues). Should these instances be removed from the default?
m5n.large
m5n.xlarge
m5n.2xlarge
m5n.4xlarge

**Comment by brooksomics** [comment]
It [used to be](https://github.com/aws-samples/aws-genomics-workflows/commit/9c081ab2f347df6bc2a044defab37a38877c834e) set to `optimal` which has always worked for me. It's not clear to me why this isn't the default ...

**Comment by wleepang** [comment]
Addressed this in #204. It will be included in the next patch release
