### ISSUE TITLE
CodeBuildInvocation leads to error

### ISSUE THREAD

**Issue by ConnorBarnhill** [aws-samples/aws-genomics-workflows#199]
Hello,

I'm trying to deploy Nextflow using [this guide](https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview.html). In the third cloudformation stack I get an error from the CodeBuildInvocation step, see below. I saw there was a closed issue that suggested specifying a version instead of using latest, however that did not fix this error. Any advice?

Received response status [FAILED] from custom resource. Message returned: Code Build job 'CodeBuildProject-8Qnu4iCPUFcp:35d3fb4d-a38f-4028-90a9-8afe78af6aef' in project 'CodeBuildProject-8Qnu4iCPUFcp' exited with a build status of 'FAILED'.

**Comment by ConnorBarnhill** [comment]
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/7959016/168909663-85ec84fc-4f62-47e8-a190-f376ed49beb5.png">

**Comment by wleepang** [comment]
Looks like the upstream Nextflow images changed, so the Dockerfile here needs to change accordingly

**Comment by wleepang** [comment]
This should be resolved with #203 and released in the next patch
