### ISSUE TITLE
Suggestions on Nextflow document flow

### ISSUE THREAD

**Issue by rspreafico-vir** [aws-samples/aws-genomics-workflows#20]
@wleepang Taking your word on providing suggestions for documentation. How open would you be to some rearrangement of the flow of the documentation for Nextflow? These are a few things that I noticed with a few suggestions, if you are open:

- Simplify architecture schematic, like Cromwell's counterpart, and using AWS official symbols (also like Cromwell)
- The Dockerfile and the nextflow entrypoint script could be provided as a repo. Possibly a runnable repo, with e.g. a makefile, or a shell script, that builds and publishes the image for you. But this is not necessary. However, I would be more explicit on the steps that a user needs to take to build & publish an image. The Dockerfile and the entrypoint script make the doc heavy, and just referencing them through a link would make the doc page lighter.
- Not immediately clear at first read what resources are created by the AIO or the Resource Cloudformation stack. The doc could start from requirements (right now it starts with the AIO stack, then requirements, then Resource stack), followed by the AIO stack (telling which points are taken care of, now it does not explicitly refers to the the list of requirements) and then the resource stack (a subset of the AIO stack, which can specify what is missing from AIO stack). IMO this flow would clarify what remains to be done manually, and would clearly reference all stacks against the list of requirements (right now, only the resource stack references requirements).
- The steps to be performed manually could be more detailed than they are now. The steps taken care of by the Cloudformation stack can be instead more concise, since only the intuition behind them needs to be provided, and not the actual step-by-step guidelines.
- In practice, nobody will have AWS CLI on each tool container, and 99.999% of the users will need the host AMI have AWS CLI. So one could jump right into that and maybe only quickly mention (in line, within brackets) that this is not necessary if ALL the tool containers already have the AWS CLI.
- Expand a little the section on actually submitting a job (from laptop? from EC2?) and monitoring it. 
- Provide examples, like Cromwell's doc page.

**Comment by rspreafico-vir** [comment]
Forgot to mention:
- stepwise, one has to build & publish the Nextflow container before running the cloudformation stack, as the address of the container is one parameter of the stack. That needs to be specified in the docs.
- the autoscaling feature is something that (if provided with an upper limit) has no drawbacks. 99.9% of the users would want that. Right now there is a note for a change requested when using autoscaling. How about instead making autoscaling default?

In general, the philosophy is to make things as turn-key as possible with defaults that make sense for most users. When this is not possible, docs should clearly guide final users step by step in the exact order they should do steps manually. Let me know if this sounds just gibberish :-)

**Comment by rspreafico-vir** [comment]
Last thing:
- can the custom AMI be provided automatically by the Cloudformation stack?

**Comment by wleepang** [comment]
@rspreafico-vir - Thanks for the input.  I'll take your points one by one:

* The icons used in the Nextflow architecture were the set released late 2018.  There's actually a new set out as of Feb that are more colorful.  (I actually need to update the Cromwell architecture with more recent icons).  How would you suggest simplifying the Nextflow architecture?

* Including the Nextflow dockerfile in the repo and linking to them is a good idea.  I'm also looking into a simple way to include building container images with a CloudFormation template, which should address your point on what is and isn't included with the AIO steps.

* Additional information can be added to clarify what is provided in the AIO.

* Can you clarify what manual steps need more details?

* Agreed, that individual tools will not be containerized with the AWS CLI.  The guide covers this and states that instances launched by Batch can have the AWS CLI installed at the host level with a Launch Template, which is included with the AIO.

* Can add more details to the job submission and monitoring section.

* Agreed.  These are in the works.  I'd also like to have community involvement here.

* Can add a note for the AIO for what users should expect to provide.

* Not clear on what autoscaling feature / request you are referring to.  The disk space autoscaling?

* A custom AMI can be created with CloudFormation.  This is how things were previously, but it proved a bit cumbersome for the need it was serving - adding a couple of small tools / scripts to the host image.  The guide favors using EC2 Launch Templates instead.

**Comment by rspreafico-vir** [comment]
Thanks @wleepang for getting back to me! Have a deadline soon but will be in touch as soon as I can!

**Comment by rspreafico-vir** [comment]
>    The icons used in the Nextflow architecture were the set released late 2018. There's actually a new set out as of Feb that are more colorful. (I actually need to update the Cromwell architecture with more recent icons). How would you suggest simplifying the Nextflow architecture?

Thanks for updating the schematic to the Feb icon set (similar to Cromwell's page). When it comes to simplifying the Nf architecture, we can split this point in simplifying the schematic of the current architecture, or simplifying the architecture itself. Here I will address the former. I think that the [Cromwell's schematic](https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-overview/) is more concise. Examples: the ECR does not have a dedicated icon and arrows in Cromwell's schematic. Similarly, job submissions do not get icons, only edges. The schematic itself is also more linearly organized, left to right. I think that simplifying the schematic in this way will allow to make it more professionally looking (on par with Cromwell) facilitating attractiveness, and will make the architecture look simpler, pretty much as simple as Cromwell's.

>    Including the Nextflow dockerfile in the repo and linking to them is a good idea. I'm also looking into a simple way to include building container images with a CloudFormation template, which should address your point on what is and isn't included with the AIO steps.

That is awesome, thank you!

>    Additional information can be added to clarify what is provided in the AIO.

Thank you! Maybe a table with resources in lines, and "Cloudformation Resources", "Cloudformation AIO" and "Manual" with checkmarks and the intersections would be the clearest. 

>    Can you clarify what manual steps need more details?

- Generally, something like "Follow these steps for the most automated setup", followed by a number list of steps, beginning to end, of the steps to be followed would be great. E.g. "1. Setup custom AMI [explanation] 2. Setup Nextflow head node [explanation] 3. Run Cloudformation AIO stack [click play here]. 
- Similarly, a list that addresses a minimal setup, entirely done manually, could also be useful - along the line of this [blog](https://antunderwood.gitlab.io/bioinformant-blog/posts/running_nextflow_on_aws_batch/). This is for users who would not require or do not have enough privileges to e.g. setup a dedicated VPC. Nextflow will still be able to work through AWS Batch in the default VPC, but this possibility could be left open (maybe even in the Cloudformation stack, with a question such as "Do you want to set up a dedicated VPC?".
- Comments on specific steps are also provided in some of the points below.

>    Agreed, that individual tools will not be containerized with the AWS CLI. The guide covers this and states that instances launched by Batch can have the AWS CLI installed at the host level with a Launch Template, which is included with the AIO.

Yes, understood. My point was that perhaps there may be no need for even a brief introduction on a scenario that won't happen for 99.9% of the users. How about jumping directly to setting up AWS CLI in the custom AMI? One can then leave a comment box saying briefly "This is not necessary if individual tools are provided through AWS CLI-able containers". Just to make the page more concise and focuses on real world scenarios.

>    Can add more details to the job submission and monitoring section.

Thank you!

>    Agreed. These are in the works. I'd also like to have community involvement here.

Thank you! I think your work is super-valuable and I am highly appreciative. You are enabling Nextflow for a large number of users who wouldn't have otherwise access to large computational clusters.

>    Can add a note for the AIO for what users should expect to provide.

That would be awesome.

>    Not clear on what autoscaling feature / request you are referring to. The disk space autoscaling?

Yes, the disk space autoscaling. It would be great if this could become the default scenario (similar to the AWS CLI, so having the disk space autoscaling is default, and a comment box could just address what to skip if one doesn't want it). If this could also be automated, so that one can have a AWS CLI-able, disk-space autoscaling custom AMI, that would be awesome. At the end of the day, creating such AMI would be necessary for all users, with very little differentiation across users, so the custom AMI could be considered a standard Nextflow requirement.

>    A custom AMI can be created with CloudFormation. This is how things were previously, but it proved a bit cumbersome for the need it was serving - adding a couple of small tools / scripts to the host image. The guide favors using EC2 Launch Templates instead.

Yes, although I didn't get from the guide whether there was a suggestion to use launch templates or whether the cloudformation stack was already taking care of this. This is only a documentation thing. As for the actual implementation, the issue with launch templates is that a overhead for installing miniconda + aws cli + autoscaling would be necessary for each instance that is launched, correct? Whereas if one creates an AMI, it is there to launch without waiting time. At the end of the day, the script to set up the custom AMI will be identical regardless of whether launch templates or AMI snapshots are chosen. So maybe this could be a decision delegated to the user by the cloudformation stack. But alternatively, if a default is necessary, seems to me that a custom AMI would be more efficient.

**Comment by rspreafico-vir** [comment]
A final point concerns the Nextflow head node. That deviates from the official Nextflow docs in that the user would not be sending AWS jobs through Nextflow directly, but through AWS Batch. I understand the convenience of this solution. Cromwell has a permanently running server that takes REST requests, so one doesn't need to call Cromwell manually from an EC2 instance (or laptop). You are attempting to provide a similar convenience with Nextflow. However, it does add a little complexity, such as Batch job specifications, need for dockerized Nextflow and custom entrypoint script. There is also no description of how this deviates from the official Nextflow docs, so that a beginner may be left wondering what the differences are about. If one wants to retain this setup, I think it would be best to highlight that this feature is not directly Nextflow-related, but it is something that the opendata instructions/cloudformation stacks are doing for the user. Having said that, is that really required? While it adds some flexibility, it also imposes some constraints. For example, the call to Nextflow is hard coded by the entrypoint script. My call to nextflow is much more complex than the invokation by the entrypoint script, for example I must pass the YAML params file - among many other flags. I wonder whether a simpler setup, with a permanently running t2.micro EC2 instance with Nextflow preinstalled would just do. No Dockerfile, no entrypoint script, simpler architecture, complete control for the user, ability to monitor job progression right away since Nextflow is launched by the user (even with the current setup, if one wants to monitor what is going on would need to login in the Nextflow head node... so logging into a permanently running EC2 instance to launch Nextflow in the first place would not be different), flexibility with command line parameters and even ability to control the launched nextflow version with NXF_VER, adherence to the nextflow official docs. What do you think? I do believe that if one wants a more sophisticated way to control Nextflow jobs through AWS that should be addressed by the Nextflow project itself, as opposed to having to work around the current limitations with the Nextflow head node. I would be happy to open a feature request with the Nextflow lead developer (who is very responsive) to get a REST interface for Nextflow like Cromwell's...

**Comment by azzaea** [comment]
Can I ask where this documentation is? I'm looking at the documentation [here](http://aws-genomics-workflows.s3-website-us-east-1.amazonaws.com/aws-batch/configure-aws-batch-start/) and it is as if anything about Nextflow has been deleted completely from the Orchestration section. 

Would you kindly advise?
Thanks,
Azza

**Comment by wleepang** [comment]
@azzaea - the official documentation site is here:
https://docs.opendata.aws/genomics-workflows

Any changes made to this repository are published there.

**Comment by wleepang** [comment]
@rspreafico-vir - I think the remaining points you brought up are addressed by PR #36.  Closing this issue for now.
