### ISSUE TITLE
Problem with Nextflow Resources CloudFormation template related to CodeBuildInvocation

### ISSUE THREAD

**Issue by MrOlm** [aws-samples/aws-genomics-workflows#200]
Hello,

When attempting to deploy the Nextflow Resources CloudFormation template (https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/nextflow/nextflow-resources.template.yaml), I receive the following error:

<img width="1893" alt="Screen Shot 2022-05-19 at 12 02 45 PM" src="https://user-images.githubusercontent.com/13424205/169381913-48b1f7db-e5d7-4ce6-b24e-b365dac346ee.png">

The error seems to be related to CodeBuildInvocation, which seems to be giving other users problems as well - https://github.com/aws-samples/aws-genomics-workflows/issues/199

This error also seems related to a previously fixed bug that was potentially recently re-introduced - https://github.com/aws-samples/aws-genomics-workflows/issues/134

One thing I've noticed that could be an issue is that the "Physical ID" of the CodeBuildInvocation has the string "[$LATEST]" in it. You can see this in the CodeBuildInvocation created in the gwfcore (screenshot below; template here: https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/gwfcore/gwfcore-code.template.yaml)

<img width="1903" alt="Screen Shot 2022-05-19 at 12 09 10 PM" src="https://user-images.githubusercontent.com/13424205/169383366-9628a2a4-3af9-4373-98a5-e16f2b9e4801.png">

You can also see in the CloudTrail logs for the Nextflow Resources CloudFormation template that a LogStream is failed to be created, again potentially due to this "[$LATEST]" string:

<img width="661" alt="Screen Shot 2022-05-19 at 12 11 36 PM" src="https://user-images.githubusercontent.com/13424205/169384281-c9e8196f-37e9-4d9b-8b19-ccfad65c9e79.png">

<img width="2245" alt="Screen Shot 2022-05-19 at 12 11 07 PM" src="https://user-images.githubusercontent.com/13424205/169384289-5821179c-e085-46fa-9b68-5146ab3a2996.png">

I'm not sure if this "[$LATEST]" string is a red herring, but it's the only hint I've come up with at trying to solve this problem.

Thanks in advance,
Matt

**Comment by berguner** [comment]
Looks like there was a problem with the NextFlow Dockerfile:
```
/usr/bin/nextflow: line 275: which: command not found
```

**Comment by brooksomics** [comment]
I'm getting the same error as @MrOlm. I'm using the most recent [commit](https://github.com/aws-samples/aws-genomics-workflows/commit/0b1739fbb328893bf1a5d7dce08fbcf614949802) and I've also included the updated `which` line in the `nextflow/`[Dockerfile](https://github.com/aws-samples/aws-genomics-workflows/pull/201).

**Comment by wleepang** [comment]
This should be resolved with #203 and released in the next patch
