### ISSUE TITLE
Charged $33 in 3 Days Trying to Run Example Workflows - Can These Workflows Run on AWS Free Tier?

### ISSUE THREAD

**Issue by felixm3** [aws-samples/aws-genomics-workflows#219]
I've been trying this week to run the example workflows:

https://aws-samples.github.io/aws-genomics-workflows/orchestration/cromwell/cromwell-examples.html

https://aws-samples.github.io/aws-genomics-workflows/orchestration/nextflow/nextflow-overview.html

Today I realized I've been charged ~$33 for the last 3 days even though I thought I get a year free since I created my AWS account last week.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/43228120/215137042-50b7a8cf-86d9-4e24-98e1-036c66c84d5f.png">

Is it possible to run any of the example workflows without getting charged?

**Comment by markjschreiber** [comment]
Worth raising a query with the support or billing teams. However, not all AWS services are Free Tier eligible so it is possibly that some of these costs are coming from those services.

**Comment by markjschreiber** [comment]
To avoid further ongoing charges you may want to delete the AWS Genomics Workflows CloudFormation stacks unless you are actively using them.

**Comment by felixm3** [comment]
> Greetings! It looks like this issue hasn’t had any activity for over three months. We encourage you to check if this is still an issue in the latest release. Because it has been longer than three months since the last update on this, and in the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please feel free to provide a comment or add an upvote to prevent automatic closure, or if the issue is already closed, please feel free to open a new one.

Not sure why this was closed even though it was open less than 3 days but I will go ahead and open it as a new issue.
