### ISSUE TITLE
Is it Possible to Run The Example Workflows Without Incurring Charges? 

### ISSUE THREAD

**Issue by felixm3** [aws-samples/aws-genomics-workflows#220]
I opened an issue 3 days ago on Friday:

https://github.com/aws-samples/aws-genomics-workflows/issues/219#issue-1560035395

and it was closed due to inactivity because I didn't respond over the weekend.

Asking the question again here: is it possible to run the example workflows 

https://aws-samples.github.io/aws-genomics-workflows/orchestration/cromwell/cromwell-examples.html

https://aws-samples.github.io/aws-genomics-workflows/orchestration/nextflow/nextflow-overview.html

without incurring charges?

I am on the AWS Free Tier until January 2024.

**Comment by felixm3** [comment]
> Greetings! It looks like this issue hasn’t had any activity for over three months. We encourage you to check if this is still an issue in the latest release. Because it has been longer than three months since the last update on this, and in the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please feel free to provide a comment or add an upvote to prevent automatic closure, or if the issue is already closed, please feel free to open a new one.

still a problem

**Comment by felixm3** [comment]
> Greetings! It looks like this issue hasn’t had any activity for over three months. We encourage you to check if this is still an issue in the latest release. Because it has been longer than three months since the last update on this, and in the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please feel free to provide a comment or add an upvote to prevent automatic closure, or if the issue is already closed, please feel free to open a new one.

still a problem

**Comment by felixm3** [comment]
> Greetings! It looks like this issue hasn’t had any activity for over three months. We encourage you to check if this is still an issue in the latest release. Because it has been longer than three months since the last update on this, and in the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please feel free to provide a comment or add an upvote to prevent automatic closure, or if the issue is already closed, please feel free to open a new one.

still a problem

**Comment by markjschreiber** [comment]
No I don't believe that is possible as is. The Cloudformation template will create some resources that are not necessarily in the free tier. This is especially true of compute types used in the AWS Batch compute environments. Free tier EC2s are not likely to be sufficient for most genomics applications.

**Comment by felixm3** [comment]
Ah. I see.

Could you add the cost of running the example workflows then as is done here please?

https://aws.amazon.com/blogs/hpc/analyzing-genomic-data-using-amazon-genomics-cli-and-amazon-sagemaker/
