### ISSUE TITLE
Issue with Cromwell on AWS

### ISSUE THREAD

**Issue by gtg269c** [aws-samples/aws-genomics-workflows#38]
Hello,
   I installed cromwell on AWS as specified in the docs https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-examples/. 

  However I am getting the follwing error. How can I address this?

Thanks
   Amin

-----------------------------------

[2019-06-01 01:19:19,55] [error] WorkflowManagerActor Workflow a45e00f9-6e1f-4382-922f-e1d00c68a3a6 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Required workflow input 'HaplotypeCallerGvcf_GATK4.MergeGVCFs.preemptible_tries' not specified
Required workflow input 'HaplotypeCallerGvcf_GATK4.HaplotypeCaller.disk_size' not specified
Required workflow input 'HaplotypeCallerGvcf_GATK4.MergeGVCFs.disk_size' not specified
Required workflow input 'HaplotypeCallerGvcf_GATK4.HaplotypeCaller.preemptible_tries' not specified

**Comment by wleepang** [comment]
@gtg269c - Thanks for pointing this out.

These parameters are not used by the AWS backend.  There are two immediate ways to resolve:

### Option 1:
Remove occurrences of the following lines from the WDL file:
```
  Int preemptible_tries
  Int disk_size
```

### Option 2:
Add the following to your `inputs.json` file:

```
  "##_COMMENT8": "DISK SIZE ALLOCATION",
  "HaplotypeCallerGvcf_GATK4.HaplotypeCaller.disk_size": 100,
  "HaplotypeCallerGvcf_GATK4.MergeGVCFs.disk_size": 100,

  "##_COMMENT9": "PREEMPTION",
  "HaplotypeCallerGvcf_GATK4.HaplotypeCaller.preemptible_tries": 3,
  "HaplotypeCallerGvcf_GATK4.MergeGVCFs.preemptible_tries": 3
```

I'll fix the example accordingly.
