### ISSUE TITLE
Source for docker images

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [aws-samples/aws-genomics-workflows#42]
Do you have specific/recommended source for docker images? I see biocontainers is popular

**Comment by wleepang** [comment]
@Parul-Kudtarkar 
There are a couple places to get pre-made docker container images.  Popular ones are [Docker Hub](hub.docker.com) and [Quay](quay.io). These host images across all segments, so you'll need to search by the name of the specific tool(s) you need images for.  [Biocontainers](https://biocontainers.pro/#/) and [Dockstore](https://dockstore.org/) are sites that provide more focused searches for bioinformatics and genomics related tools.  They will still provide links / instructions for pulling the images from either Docker Hub or Quay.
