### ISSUE TITLE
cromwell example

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [aws-samples/aws-genomics-workflows#45]
I was running s[imple-hello.wdl example](https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-examples/), however in batch console the status was runnable for over 15 minutes!

**Comment by wleepang** [comment]
@Parul-Kudtarkar 

I just tested this with a new stack created in `us-west-2` and didn't get such a delay.

Did your job eventually start? It would be helpful if you could provide details on the stack you created and how you ran the example.  For example, did you modify the Maximum vCPU count?

**Comment by Parul-Kudtarkar** [comment]
@wleepang it ran this time without any issues. I used ditto stack parameters as I did last time, I am not sure what caused it to be in runnable state. Thanks for checking & responding!
