### ISSUE TITLE
403 when downloading aws-batch-genomics.tar.gz

### ISSUE THREAD

**Issue by kdi-insitro** [aws-samples/aws-genomics-workflows#47]
Issue in `cloud-init-userdata.yaml` where cloud-init fails to download the aws-batch-genomics.tar.gz likely because of a 403 error:

`$ wget https://aws-genomics-workflows.s3.amazonaws.com/aws-batch-genomics.tar.gz
--2019-06-26 13:20:12--  https://aws-genomics-workflows.s3.amazonaws.com/aws-batch-genomics.tar.gz
Resolving aws-genomics-workflows.s3.amazonaws.com (aws-genomics-workflows.s3.amazonaws.com)... 52.217.1.212
Connecting to aws-genomics-workflows.s3.amazonaws.com (aws-genomics-workflows.s3.amazonaws.com)|52.217.1.212|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-06-26 13:20:13 ERROR 403: Forbidden.`

**Comment by golharam** [comment]
The path is wrong.  It should be https://s3.amazonaws.com/aws-genomics-workflows/artifacts/aws-ebs-autoscale.tgz
