### ISSUE TITLE
No project name was specified

### ISSUE THREAD

**Issue by matthpich** [aws-samples/aws-genomics-workflows#58]
Hi,
I am trying to run the simple hello.nf workflow but with no success.
I keep receiving a "No project name was specified".
Do you know how to solve that?
Many thanks for your help.
M

cmd:
```
aws batch submit-job
--job-name hello     
--job-queue <queue>
--job-definition nextflow
--container-overrides command=s3://nextflow.run/script/hello.nf
```

hello.nf:
```
texts = Channel.from("AWS", "Nextflow")

process hello {
    // directives
    // a container images is required
    container "ubuntu:latest"

    // compute resources for the Batch Job
    cpus 1
    memory '512 MB'

    input:
    val text from texts

    output:
    file 'hello.txt'

    """
    echo "Hello $text" > hello.txt
    """
}
```

**Comment by wleepang** [comment]
@matthpich - how recently have you deployed the infrastructure - specifically the `nextflow` container.  There was a small typo in the entrypoint script that was recently resolved.

Otherwise, does your workflow still run?

**Comment by matthpich** [comment]
I deployed the infrastructure one week ago.

**Comment by wleepang** [comment]
Noticing that your command points to the `*.nf` script directly.  The entrypoint expects the script to have other files associated with it (e.g. additional config, data assests, etc) similar workflows from NF-Core.  It uses `s3 sync` to retrieve these.  Try the following - pointing to the parent folder above the `*.nf` script:

```
aws batch submit-job
--job-name hello     
--job-queue <queue>
--job-definition nextflow
--container-overrides command=s3://nextflow.run/script/
```

**Comment by wleepang** [comment]
Closing this issue.  Feel free to reopen if you are still having problems.
