### ISSUE TITLE
ScratchMountPoint set incorrectly on Cromwell Full Stack Deployment

### ISSUE THREAD

**Issue by caaespin** [aws-samples/aws-genomics-workflows#59]
When doing a Cromwell Full Stack Deployment as showed [here](https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-overview/), when inspecting EC2 Launche Template portion of the stack, the ScratchMountPoint parameter is set to `/scratch`, but not `/cromwell_root`, which I believe is what is causing a lot of out of disk space errors on my side.

**Comment by wleepang** [comment]
@caaespin - the scratch mount point is set here:
https://github.com/aws-samples/aws-genomics-workflows/blob/73ab29f1b6152417da622f55594f3af87d096253/src/templates/aws-genomics-launch-template.template.yaml#L145

using a mapping:
https://github.com/aws-samples/aws-genomics-workflows/blob/73ab29f1b6152417da622f55594f3af87d096253/src/templates/aws-genomics-launch-template.template.yaml#L158
https://github.com/aws-samples/aws-genomics-workflows/blob/73ab29f1b6152417da622f55594f3af87d096253/src/templates/aws-genomics-launch-template.template.yaml#L7

From what I can tell, this should pick up the orchestrator ("cromwell") correctly and override the default of `/scratch` accordingly.

Can you verify in the created launch template that this is not being set correctly?

**Comment by wleepang** [comment]
Closing this issue.  Feel free to reopen if you are still having problems.
