### ISSUE TITLE
Update to work for Amazon Linux 2

### ISSUE THREAD

**Issue by gilfreund** [aws-samples/aws-genomics-workflows#62]
Is there a plan to update these tools for Amazon Linux 2 (e.g. systemd, amazon-linux-extras)?

**Comment by wleepang** [comment]
@gilfreund - can you provide more specifics?  Is something not working in Amazon Linux 2?  AWS Batch defaults to the ECS Optimized AMI based on Amazon Linux 1.

**Comment by gilfreund** [comment]
We have encountered this as we were building our templates for AWS batch. We were using the latest Amazon Linux 2 ECS AMI. Our scripts are built with it and therefor have various dependencies and assumptions regrading AL2 yum package names, binary locations and systemd structure.
We came across aws-genomics-workflows later, and we like it very much.

If there are no plans to modify the code for AL2, then I guess we will look into back-porting our scripts to AL1, or, time permitting, have a go at hacking aws-genomics-workflows for AL2.

**Comment by wleepang** [comment]
At the moment there aren't plans to port to Amazon Linux 2.  If you specifically require it - i.e. you aren't able to get the results / capabilities you need with Amazon Linux 1 - let me know, and I can take that as feedback for AWS Batch.

**Comment by gilfreund** [comment]
This is similar to the response I got from AWS support, there is no specific timeline to move AWS batch default from AL1 to AL2. I don't see a specific functionality I am missing in AL1, but as we are already basing our scripting on AL2, I was hoping to avoid two code bases, and a future need to refactor. 
I think the main differences are in the way packages are retrieved (python package names, getting docker via amazon-linux-extras instead of yum) and services configuration files and control commands. I believe we can make those modifications ourselves. 
I am closing this case.
Thanks for your feedback

**Comment by mcnelsonsema4** [comment]
Hold on, from AWS's own guide on Amazon ECS-optimized AMIs AL1 support should be ending in less than a year.

> Amazon ECS-optimized Amazon Linux AMI – This AMI is based off of Amazon Linux 1. We recommend that you migrate your workloads to the Amazon ECS-optimized Amazon Linux 2 AMI. Support for the Amazon ECS-optimized Amazon Linux AMI ends no later than June 30, 2020.

This means we should move to prefer AL2 over AL1 now so everything is future-proofed as AL2 is the primary linux distro for AWS.

@gilfreund , I have actually been working on converting the EBS autoscaling part to systemd, when I get that sorted I can create a PR but it would force AL2. I guess the autoscale package could be renamed to `aws-ebs-autoscale-al2` and there's a mapping in the CF template for which version based on which AMI...?

**Comment by wleepang** [comment]
The code for EBS Autoscale has been moved to a separate repository:
https://github.com/awslabs/amazon-ebs-autoscale

In doing so, I added support for `systemd` and Amazon Linux 2.
