### ISSUE TITLE
Using EBS Autoscale on Amazon Linux 2

### ISSUE THREAD

**Issue by godotgildor** [aws-samples/aws-genomics-workflows#76]
I'm trying to setup the EBS Autoscale system on an instance using the ECS-Optimized Amazon Linux 2. I wanted to do it once by hand prior to leveraging the Launch Template.

I launched a t2-micro with the two additional EBS volumes attached as described. I then used `yum` to install the set of packages:
```
yum install -y jq btrfs-progs python-pip sed wget
```

I then downloaded and extracted the tar ball. Running 
```
sh /opt/ebs-autoscale/bin/init-ebs-autoscale.sh /scratch /dev/sdc
```
works about half way. Once it gets to the part where it is using sed to update the conf template and place the actual conf file in `/etc/init`, it fails since that directory does not exist. It then fails when calling `initctl` saying `command not found`. 

My guess is that this has something to do with Amazon Linux 2 using systemd init system? I'm not familiar enough with that system to update the scripts here easily, but wanted to check if you had any suggestions.

**Comment by wleepang** [comment]
Correct.  The solution at the moment only supports Amazon Linux 1.  (See also #62)

**Comment by wleepang** [comment]
The code for EBS Autoscale has been moved to a separate repository:
https://github.com/awslabs/amazon-ebs-autoscale

In doing so, I added support for `systemd` and Amazon Linux 2.
