### ISSUE TITLE
StackOverFlow error

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [aws-samples/aws-genomics-workflows#77]
Hi,

We are trying to run the nf-core atac-seq pipeline, 
`jason@jason-XPS-13-9370: ./nextflow run nf-core/atacseq --input 's3://jason-bucket/design.csv' --fasta 's3://jason-bucket/genome.fa' --gtf 's3://jason-bucket/genes.gtf' -profile awsbatch --awsregion eu-west-2 --awsqueue highpriority-d8b23a90-16a7-11ea-ac48-0aad4e0395e8 --outdir 's3://jason-bucket/results' --save_reference`
we get following error
```
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/atacseq` [voluminous_lavoisier] - revision: fa1e3f8993 [master]
Unexpected error [StackOverflowError]
```
Any idea on how to resolve this? Thanks!

**Comment by wleepang** [comment]
@Parul-Kudtarkar - Apologies for the delay.  I presume you solved your issue?  Can you share what the cause was?

**Comment by Parul-Kudtarkar** [comment]
Hi @wleepang! According to nextflow developer, this is a known bug. which may be bypassed by downloading this file:
https://github.com/nf-core/atacseq/blob/master/conf/awsbatch.config
Renaming it to say aws.config and then adding -c aws.config to the command.
