### ISSUE TITLE
Change from NAT gateway to egress only gateway or public IPs

### ISSUE THREAD

**Issue by snamburi3** [aws-samples/aws-genomics-workflows#80]
The NAT gateway in private subnet to download, process, and then transfer the genomics data via NAT Gateway will be costly. I had to modify the network quite a bit. We are using public IPs with no-inbound security group and NACLs. 
I will upload the configuration changes later. Do you recommend any other setup?

**Comment by wleepang** [comment]
You can setup an S3 endpoint for the VPC so that instances in private subnets can retrieve data without transferring over the public internet.

**Comment by wleepang** [comment]
Closing this issue for now.  Feel free to re-open if needed.
