### ISSUE TITLE
Running nextflow ATACseq pipeline

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [aws-samples/aws-genomics-workflows#84]
Hi @wleepang 

I am implementing nextflow ATACseq pipeline.
`aws batch submit-job --job-name run-workflow-nf --job-queue highpriority-x --job-definition nextflow --container-overrides command=s3://test-atacseq,"--input","'s3://atacseq/design.csv'","--fasta","'s3://atacseq/genome.fa'","--gtf","'s3://atacseq/genes.gtf'","--outdir","'s3://atacseq/results'"`
I get following error
An error occurred (ClientException) when calling the SubmitJob operation: JobDefinition name nextflow does not exist or is not in ACTIVE status

**Comment by Parul-Kudtarkar** [comment]
![Screen Shot 2020-01-15 at 4 48 40 PM](https://user-images.githubusercontent.com/22722805/72483786-0c1d2180-37b7-11ea-82a1-27414cbcf891.png)

**Comment by wleepang** [comment]
@Parul-Kudtarkar - try adding a `--region` flag to your AWS CLI call referencing the region that you have the batch job queue and job definition.

**Comment by Parul-Kudtarkar** [comment]
@wleepang Great! That works. TYVM!

**Comment by OnePercentAt** [comment]
> @Parul-Kudtarkar - try adding a `--region` flag to your AWS CLI call referencing the region that you have the batch job queue and job definition.

this was what I needed exactly.  Thank you.
