### ISSUE TITLE
cluster size

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [aws-samples/aws-genomics-workflows#85]
Hi @wleepang 

Apart from the rnaseq pipline demo-ed in this document, I was successfully able to test Nextflow's atacseq pipeline using the cloudformation templates. I typically see 1-3 instances (M5 & R4) launched as the pipeline progresses. Is there a way I can spawn more instances/larger cluster to expedite the computation or is the process/cloudformation template able to  automate based on number of input samples i.e. I tested it with a single sample; would it scale up if I add additional samples?

**Comment by wleepang** [comment]
Hi @Parul-Kudtarkar 

That would depend on how parallelism is built into the workflow.  A pattern I typically see is one invocation of a workflow for one sample.  A nextflow master process runs one workflow per call.  So if you had 100 samples to process with workflow X, you would make 100 nextflow AWS Batch Job submissions – each processing a sample.  AWS Batch will scale accordingly.
 
If the workflow you are using takes multiple samples as input and processes them in parallel, then nextflow will spawn as many parallel jobs as needed.  The instance sizes will depend on a couple things:

1. How many vCPUs a compute environment allows (Max vCPUs)
2. How many vCPUs individual jobs require
3. How many jobs nextflow or the workflow will submit concurrently

By default, and for cost efficiency, Batch will try to pack as many jobs as it can into one instance.  So you could see a couple of beefy instances (e.g. r4.8xl) launched to run 50+ jobs.
 
Hope this helps.

**Comment by Parul-Kudtarkar** [comment]
Thank you very much!
