### ISSUE TITLE
Add Python CDK constructs

### ISSUE THREAD

**Issue by cfriedline** [aws-samples/aws-genomics-workflows#87]
Per @wleepang, I am opening this issue to begin work on planning and integrating [AWS CDK](https://aws.amazon.com/cdk/) constructs into this repository as a companion to (or eventual replacement of) the raw CloudFormation templates.

**Comment by wleepang** [comment]
Thanks @cfriedline !
I've created a corresponding branch for development: develop/cdk-constructs

**Comment by henriqueribeiro** [comment]
Hey,

I have some time that I can spend on this. Is it still something that we would like to have?
