### ISSUE TITLE
S3 error: Access Denied error when trying to launch a "AWS Step Functions Example"

### ISSUE THREAD

**Issue by mogilp** [aws-samples/aws-genomics-workflows#90]
When tried to launch the stack for "AWS Step Functions Example" from "Step 2: Worklow Orchestrators" from the link https://docs.opendata.aws/genomics-workflows/quick-start/

Running into "S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html" error. 
````````
curl https://s3.amazonaws.com/aws-genomics-workflows/templates/step-functions/sfn-example.template.yaml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>A1ABEA1C97F3B96B</RequestId><HostId>QpIr+GUOOCiLTHEN0B4BXfp5KlCwQNrwwGdGAO9RRfiZqfaGYTQd3oKzBPG5RsuhPl+5F18EWUM=</HostId></Error>
`````````
Please look into it!

**Comment by wleepang** [comment]
Looks like the template uri didn't get updated in that spot.  The launch link here is what the "quick-start" link is supposed to point to:
https://docs.opendata.aws/genomics-workflows/orchestration/step-functions/step-functions-overview/#example-state-machine

It'll be corrected in the next release.
