### ISSUE TITLE
All our cromwell aws backend deployments cease to work today

### ISSUE THREAD

**Issue by lij41** [aws-samples/aws-genomics-workflows#92]
I think it must be something to do yesterday's v2.6.0 release.  Today, all our aws-genomics-workflows deployments in our several account ceased to work suddenly.  Our aws-genomics-workflows  version in those accounts is v2.3.0

All the error messages is  "no space left on device".

We are in critical production release time. Your immediate attention and help will be highly appreciated!

Thanks
Jing

**Comment by wleepang** [comment]
@lij41 - the `ebs-autoscale.tgz` artifact was removed with the latest release since code for it was moved to its own repository.  I've regenerated the tarball and am developing a compatibility shim.

Apologies for the inconvenience.

**Comment by lij41** [comment]
Great.  Thanks. All the new releases should be backward compatible.  Let us know once you fixed the issue.

**Comment by lij41** [comment]
In the old version of aws-genomics-workflows, each deployment will create a permanent custom AMI, in this scenario, the new release will only effect the new deployment.  Since we are using launch template, the deployment seems no longer generate permanent custom AMI, it run those template every time creating a new EC2 instance, which means it directly effect the production's daily operations.  Do you have a good suggestion to overcome such issue?

Thanks and Best Wishes
Jing

**Comment by wleepang** [comment]
Can you specify what your key requirements are - e.g. eliminating external dependencies during instance launch?

**Comment by sworisbreathing** [comment]
We ran into issues with the changes as well, because our environment sits inside a VPC with a nat proxy and can't access GitHub. We ended up having to mirror the ebs autoscaling tarball in our own S3 bucket.

Have a look at the latest launch template in this repo. The names of some of the scripts have changed as well.

It'd be much better for the user experience if the old location on S3 was a mirror of the github releases though.

**Comment by wleepang** [comment]
@sworisbreathing 

> We ran into issues with the changes as well, because our environment sits inside a VPC with a nat proxy and can't access GitHub. We ended up having to mirror the ebs autoscaling tarball in our own S3 bucket.

Are you able to still `curl` to `https://api.github.com/` and `https://github.com` - i.e. is it an option to download the amazon-ebs-autoscale release tarballs that way?  Or is your VPC completely isolated from the public internet and you can only access S3 via a VPC Endpoint?

**Comment by sworisbreathing** [comment]
@wleepang - yep, all access to AWS resources is done through VPC endpoints. No direct internet access from within the VPC. GitHub is not accessible at all.

**Comment by wleepang** [comment]
This issue should be resolved in the latest patch. Closing for now. Feel free to reopen if you continue to have issues.

**Comment by lij41** [comment]
@wleepang Are you sure it really worked?  In late day of 02/28/20, we start seeing a lot of job failure due to "no space left on device" AGAIN, and it happened at our several accounts.  I am wondering if the patch cause this.

We have a stable system for a few days, now it happened again, make me blame this new patch.

Can you take a look at your earliest convenience?  We did a lot of product development on v2.3.0, and we are at the verge of product release.  We need to do considerable tests to gain certain confidence to upgrade v2.6.x. We do not have that time right now.  Your help will be greatly appreciated.

THanks
Jing

**Comment by wleepang** [comment]
There was a typo in the compatibility shim script.  The latest patch release corrects it.

I also verified that the latest shims for ebs-autoscale work with the 2.3.x version of the LaunchTemplate by launching an instance directly from the LaunchTemplate and checking `/var/log/cloud-init-output.log` and `/var/log/init-ebs-autoscale.log`.
