### ISSUE TITLE
IOException trying to access the public reference data

### ISSUE THREAD

**Issue by blindmouse** [aws-samples/aws-genomics-workflows#98]
Hi there,

I was trying to replicate the HaplotyperCaller example at https://docs.opendata.aws/genomics-workflows/orchestration/cromwell/cromwell-examples/ The hello world ones and the read file works, but not the HaplotyperCaller one. I received an error message saying IOException: Could not read from s3://gatk-test-data/intervals/hg38_wgs_scattered_calling_intervals.txt: Cannot access file: s3://s3.amazonaws.com/gatk-test-data/intervals/hg38_wgs_scattered_calling_intervals.txt . I googled the message and tried to vary the docker image, memory, and disk size. But none of these works. Could you help me figure out what is wrong with this example, please? Thanks!

**Comment by markjschreiber** [comment]
I have also seen this error. It is because the IAM role used by Cromwell (as defined by the default cloudformation template) doesn’t specify access to this bucket. Two possible solutions: add all the required buckets to the IAM roles policy, or copy the required files to your Cromwell bucket

**Comment by blindmouse** [comment]
Thank you. 
However, if I run the example "Using data on S3", changing the content of s3input.json to:
{
  "ReadFile.read_file.file": "s3://gatk-test-data/intervals/hg38_wgs_scattered_calling_intervals.txt"
}
This one runs successfully without changing the IAM role policy. If the HaplotyperCaller example failed because of IAM role does not specify access to this bucket, shouldn't this fail as well?

But I'll try changing the IAM role policy anyway.

**Comment by blindmouse** [comment]
> I have also seen this error. It is because the IAM role used by Cromwell (as defined by the default cloudformation template) doesn’t specify access to this bucket. Two possible solutions: add all the required buckets to the IAM roles policy, or copy the required files to your Cromwell bucket

Sorry, it still did not work when I changed the IAM roles policy.

**Comment by wleepang** [comment]
Re-encountered this issue recently. The reason is because the underlying `s3fs` java library used by Cromwell creates an S3 client session with a region. The net effect is that you either have to run your cromwell-server in the same region as the Open Datasets (us-east-1) or set `aws { region = us-east-1 }` in `cromwell.conf`.
